<?php

namespace Database\Seeders;

use App\Models\Opportunity;
use App\Models\OpportunityType;
use App\Models\Country;
use App\Models\Category;
use Illuminate\Database\Seeder;

class OpportunitySeeder extends Seeder
{
    public function run(): void
    {
        $types = OpportunityType::pluck('id', 'slug')->all();
        $countries = Country::pluck('id', 'slug')->all();
        $categories = Category::pluck('id', 'slug')->all();

        $opportunities = [
            [
                'title' => json_encode(['en' => 'Turkish Government Scholarship for Bachelor\'s and Graduate Studies 2025']),
                'slug' => 'turkish-government-scholarship-2025',
                'excerpt' => json_encode(['en' => 'A fully funded scholarship from the Turkish government covering tuition, housing, health insurance, and a monthly stipend.']),
                'content' => json_encode(['en' => '<h2>Turkish Government Scholarship (Türkiye Bursları) 2025</h2><p>The Turkish government offers fully funded scholarships to international students from around the world to study at top Turkish universities.</p><h3>Scholarship Benefits</h3><ul><li>Full tuition coverage</li><li>Free university housing</li><li>Comprehensive health insurance</li><li>Monthly stipend: 1000 TL for bachelor\'s, 1400 TL for master\'s, 1800 TL for PhD</li><li>Round-trip flight ticket</li><li>A preparatory year to learn Turkish</li></ul><h3>Application Requirements</h3><ul><li>The applicant must be from outside Turkey</li><li>A minimum GPA of 70% for bachelor\'s</li><li>A minimum GPA of 75% for graduate studies</li><li>Maximum age of 21 for bachelor\'s, 30 for master\'s, 35 for PhD</li></ul>']),
                'opportunity_type_id' => $types['scholarship'] ?? null,
                'category_id' => $categories['bachelor'] ?? null,
                'country_id' => $countries['turkey'] ?? null,
                'organization' => 'Turkish Government',
                'funding_type' => 'Fully Funded',
                'education_level' => 'Bachelor\'s, Master\'s, PhD',
                'application_deadline' => '2026-02-20',
                'application_url' => 'https://www.turkiyeburslari.gov.tr',
                'official_source_url' => 'https://www.turkiyeburslari.gov.tr',
                'benefits' => json_encode(['en' => ['Full tuition', 'Free housing', 'Health insurance', 'Monthly stipend', 'Flight ticket', 'Preparatory language year']]),
                'eligibility' => json_encode(['en' => ['Nationality: non-Turkish', 'GPA: 70%+ bachelor\'s, 75%+ graduate', 'Age: under 21 for bachelor\'s, under 30 for master\'s, under 35 for PhD']]),
                'required_documents' => json_encode(['en' => ['Passport', 'Academic certificates', 'Transcripts', 'Motivation letter', 'Recommendation letters', 'Language certificate if available']]),
                'application_process' => json_encode(['en' => ['Register via the official website', 'Upload documents', 'Choose majors and universities', 'Personal interview', 'Admission result']]),
                'status' => 'published',
                'is_featured' => true,
                'published_at' => '2026-01-15',
            ],
            [
                'title' => json_encode(['en' => 'Software Developer Job at a Major Tech Company in Saudi Arabia']),
                'slug' => 'software-developer-job-saudi-arabia',
                'excerpt' => json_encode(['en' => 'A distinguished job opportunity for software developers at a leading tech company in Riyadh with a salary of up to 25,000 SAR per month.']),
                'content' => json_encode(['en' => '<h2>Senior Software Developer - Riyadh</h2><p>A leading tech company in Riyadh is looking for experienced software developers to join its development team.</p><h3>Requirements</h3><ul><li>3+ years of experience in web development</li><li>Proficiency in Laravel and React</li><li>Knowledge of MySQL and PostgreSQL databases</li><li>Experience working with REST APIs</li></ul><h3>Benefits</h3><ul><li>Salary: 20,000 - 25,000 SAR</li><li>Health insurance</li><li>Housing and transportation allowance</li><li>Continuous professional development</li></ul>']),
                'opportunity_type_id' => $types['job'] ?? null,
                'category_id' => $categories['it'] ?? null,
                'country_id' => $countries['saudi-arabia'] ?? null,
                'organization' => 'Leading Tech Company',
                'funding_type' => 'Salaried',
                'employment_type' => 'Full-time',
                'salary_amount' => 25000,
                'salary_currency' => 'SAR',
                'salary_period' => 'Monthly',
                'application_deadline' => '2026-03-01',
                'application_url' => 'https://example.com/apply',
                'status' => 'published',
                'is_featured' => true,
                'published_at' => '2026-02-01',
            ],
            [
                'title' => json_encode(['en' => 'Qatar University Graduate Scholarship 2026']),
                'slug' => 'qatar-university-graduate-scholarship-2026',
                'excerpt' => json_encode(['en' => 'Qatar University\'s master\'s and PhD scholarship covering tuition, accommodation, tickets, and a monthly stipend.']),
                'content' => json_encode(['en' => '<h2>Qatar University Graduate Scholarship</h2><p>Qatar University offers competitive scholarships to outstanding students of all nationalities to pursue master\'s and PhD studies.</p><h3>Benefits</h3><ul><li>Tuition fee waiver</li><li>University housing</li><li>Annual flight tickets</li><li>Monthly stipend of 5000 QAR</li></ul>']),
                'opportunity_type_id' => $types['scholarship'] ?? null,
                'category_id' => $categories['master'] ?? null,
                'country_id' => $countries['qatar'] ?? null,
                'organization' => 'Qatar University',
                'funding_type' => 'Fully Funded',
                'education_level' => 'Master\'s, PhD',
                'application_deadline' => '2026-04-15',
                'application_url' => 'https://www.qu.edu.qa',
                'status' => 'published',
                'is_featured' => true,
                'published_at' => '2026-01-20',
            ],
            [
                'title' => json_encode(['en' => 'Arab Youth Innovation & Entrepreneurship Conference 2026']),
                'slug' => 'arab-youth-innovation-conference-2026',
                'excerpt' => json_encode(['en' => 'An annual conference bringing together innovative Arab youth and entrepreneurs in Dubai to exchange experience and build networks.']),
                'content' => json_encode(['en' => '<h2>Arab Youth Innovation Conference</h2><p>The conference brings together more than 1000 young men and women from the Arab world to discuss innovation, entrepreneurship, and technology.</p>']),
                'opportunity_type_id' => $types['conference'] ?? null,
                'category_id' => $categories['business'] ?? null,
                'country_id' => $countries['uae'] ?? null,
                'organization' => 'Arab Youth Organization',
                'application_deadline' => '2026-05-30',
                'application_url' => 'https://example.com/conference',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-03-01',
            ],
            [
                'title' => json_encode(['en' => 'Saudi Aramco Graduate Training Program']),
                'slug' => 'aramco-graduate-training-program-2026',
                'excerpt' => json_encode(['en' => 'A training-to-hire program at Saudi Aramco for graduates in engineering, science, and technology.']),
                'content' => json_encode(['en' => '<h2>Training-to-Hire Program - Aramco</h2><p>Saudi Aramco offers an intensive training program for Saudi graduates in various engineering and technical specializations.</p><h3>Benefits</h3><ul><li>Monthly stipend during the training period</li><li>Health insurance</li><li>Employment opportunity after completing the program</li><li>Professional development and accredited certificates</li></ul>']),
                'opportunity_type_id' => $types['training'] ?? null,
                'category_id' => $categories['engineering'] ?? null,
                'country_id' => $countries['saudi-arabia'] ?? null,
                'organization' => 'Saudi Aramco',
                'funding_type' => 'Training Stipend',
                'application_deadline' => '2026-06-10',
                'application_url' => 'https://www.aramco.com',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-02-15',
            ],
            [
                'title' => json_encode(['en' => 'King Abdullah University of Science and Technology (KAUST) Scholarship']),
                'slug' => 'kaust-scholarship-2026',
                'excerpt' => json_encode(['en' => 'A comprehensive scholarship at King Abdullah University of Science and Technology for master\'s and PhD studies.']),
                'content' => json_encode(['en' => '<h2>KAUST Scholarship</h2><p>King Abdullah University of Science and Technology offers competitive scholarships in science, engineering, and technology fields.</p><h3>Benefits</h3><ul><li>Full tuition</li><li>Annual stipend of up to $30,000</li><li>Free housing</li><li>Health insurance</li></ul>']),
                'opportunity_type_id' => $types['scholarship'] ?? null,
                'category_id' => $categories['engineering'] ?? null,
                'country_id' => $countries['saudi-arabia'] ?? null,
                'organization' => 'King Abdullah University of Science and Technology',
                'funding_type' => 'Fully Funded',
                'education_level' => 'Master\'s, PhD',
                'salary_amount' => 30000,
                'salary_currency' => 'USD',
                'salary_period' => 'Annual',
                'application_deadline' => '2026-07-01',
                'application_url' => 'https://www.kaust.edu.sa',
                'status' => 'published',
                'is_featured' => true,
                'published_at' => '2026-03-01',
            ],
            [
                'title' => json_encode(['en' => 'Huawei ICT Global Competition 2026']),
                'slug' => 'huawei-ict-competition-2026',
                'excerpt' => json_encode(['en' => 'Huawei\'s global ICT competition for students, with valuable prizes and training opportunities.']),
                'content' => json_encode(['en' => '<h2>Huawei ICT Competition 2026</h2><p>A global competition covering cloud computing, artificial intelligence, and networking.</p><h3>Prizes</h3><ul><li>First place: $20,000</li><li>Accredited certificates from Huawei</li><li>Training opportunities at Huawei centers</li></ul>']),
                'opportunity_type_id' => $types['competition'] ?? null,
                'category_id' => $categories['it'] ?? null,
                'organization' => 'Huawei',
                'funding_type' => 'Cash Prize',
                'application_deadline' => '2026-08-15',
                'application_url' => 'https://www.huawei.com/ict',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-04-01',
            ],
            [
                'title' => json_encode(['en' => 'Germany Job Seeker Visa for Skilled Professionals']),
                'slug' => 'germany-job-seeker-visa-2026',
                'excerpt' => json_encode(['en' => 'A 6-month job seeker visa in Germany for skilled professionals holding university degrees.']),
                'content' => json_encode(['en' => '<h2>Germany Job Seeker Visa</h2><p>Germany allows skilled professionals from outside the EU to obtain a job seeker visa for 6 months.</p><h3>Requirements</h3><ul><li>A recognized university degree</li><li>Proof of financial capability</li><li>Health insurance</li></ul>']),
                'opportunity_type_id' => $types['visa'] ?? null,
                'country_id' => $countries['germany'] ?? null,
                'organization' => 'German Embassy',
                'application_deadline' => null,
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-04-10',
            ],
            [
                'title' => json_encode(['en' => 'Qatar Foundation for Education, Science and Community Development Scholarship']),
                'slug' => 'qatar-foundation-scholarship-2026',
                'excerpt' => json_encode(['en' => 'Scholarships from Qatar Foundation for outstanding students in various majors at the partner universities in Education City.']),
                'content' => json_encode(['en' => '<h2>Qatar Foundation Scholarship</h2><p>Qatar Foundation offers scholarships at world-class universities within Education City, such as Georgetown University, Northwestern University, and Texas A&M University.</p>']),
                'opportunity_type_id' => $types['scholarship'] ?? null,
                'category_id' => $categories['bachelor'] ?? null,
                'country_id' => $countries['qatar'] ?? null,
                'organization' => 'Qatar Foundation',
                'funding_type' => 'Fully Funded',
                'education_level' => 'Bachelor\'s',
                'application_deadline' => '2026-06-30',
                'application_url' => 'https://www.qf.org.qa',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-05-01',
            ],
            [
                'title' => json_encode(['en' => 'Volunteer Opportunity at the United Nations Youth Program']),
                'slug' => 'un-youth-volunteer-program-2026',
                'excerpt' => json_encode(['en' => 'The UN Youth Volunteer Programme offers international volunteering opportunities with a stipend, tickets, and insurance.']),
                'content' => json_encode(['en' => '<h2>United Nations Volunteers Programme</h2><p>The UN Volunteers Programme offers opportunities for young people to contribute to development projects around the world.</p><h3>Benefits</h3><ul><li>Monthly stipend</li><li>Flight tickets</li><li>Health insurance</li><li>Paid annual leave</li></ul>']),
                'opportunity_type_id' => $types['volunteering'] ?? null,
                'organization' => 'United Nations',
                'funding_type' => 'Volunteer Stipend',
                'application_deadline' => '2026-09-30',
                'application_url' => 'https://www.unv.org',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-05-15',
            ],
            [
                'title' => json_encode(['en' => 'Medicine Scholarship at Cairo University']),
                'slug' => 'cairo-university-medicine-scholarship-2026',
                'excerpt' => json_encode(['en' => 'A scholarship for Arab students to study human medicine at the prestigious Cairo University.']),
                'content' => json_encode(['en' => '<h2>Medicine Scholarship at Cairo University</h2><p>Cairo University offers scholarships to outstanding Arab students to study human medicine.</p>']),
                'opportunity_type_id' => $types['scholarship'] ?? null,
                'category_id' => $categories['medicine'] ?? null,
                'country_id' => $countries['egypt'] ?? null,
                'organization' => 'Cairo University',
                'funding_type' => 'Partially Funded',
                'education_level' => 'Bachelor\'s',
                'application_deadline' => '2026-08-01',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-06-01',
            ],
            [
                'title' => json_encode(['en' => 'Translator Job at the British Embassy in Riyadh']),
                'slug' => 'translator-job-british-embassy-riyadh',
                'excerpt' => json_encode(['en' => 'An Arabic-English translator position at the British Embassy in Riyadh with a rewarding salary.']),
                'content' => json_encode(['en' => '<h2>Translator - British Embassy in Riyadh</h2><p>The British Embassy in Riyadh is looking for a professional translator for Arabic-English translation.</p>']),
                'opportunity_type_id' => $types['job'] ?? null,
                'country_id' => $countries['saudi-arabia'] ?? null,
                'organization' => 'British Embassy',
                'employment_type' => 'Full-time',
                'salary_amount' => 18000,
                'salary_currency' => 'SAR',
                'salary_period' => 'Monthly',
                'application_deadline' => '2026-03-20',
                'status' => 'closed',
                'is_featured' => false,
                'published_at' => '2026-01-10',
            ],
        ];

        foreach ($opportunities as $data) {
            Opportunity::firstOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
