<?php

namespace Database\Seeders;

use App\Models\Opportunity;
use App\Models\OpportunityType;
use App\Models\Country;
use App\Models\Category;
use Illuminate\Database\Seeder;

class OpportunitySeeder extends Seeder
{
    public function run(): void
    {
        $types = OpportunityType::pluck('id', 'slug')->all();
        $countries = Country::pluck('id', 'slug')->all();
        $categories = Category::pluck('id', 'slug')->all();

        $opportunities = [
            [
                'title' => json_encode(['ar' => 'منحة الحكومة التركية للبكالوريوس والدراسات العليا 2025']),
                'slug' => 'turkish-government-scholarship-2025',
                'excerpt' => json_encode(['ar' => 'منحة دراسية ممولة بالكامل من الحكومة التركية تشمل الرسوم الدراسية والسكن والتأمين الصحي وراتب شهري.']),
                'content' => json_encode(['ar' => '<h2>منحة الحكومة التركية (Türkiye Bursları) 2025</h2><p>تقدم الحكومة التركية منحًا دراسية ممولة بالكامل للطلاب الدوليين من جميع أنحاء العالم للدراسة في أرقى الجامعات التركية.</p><h3>مزايا المنحة</h3><ul><li>تغطية كاملة للرسوم الدراسية</li><li>سكن جامعي مجاني</li><li>تأمين صحي شامل</li><li>راتب شهري: 1000 ليرة للبكالوريوس، 1400 ليرة للماجستير، 1800 ليرة للدكتوراه</li><li>تذكرة طيران ذهاب وعودة</li><li>سنة تحضيرية لتعلم اللغة التركية</li></ul><h3>شروط التقديم</h3><ul><li>أن يكون المتقدم من خارج تركيا</li><li>معدل لا يقل عن 70% للبكالوريوس</li><li>معدل لا يقل عن 75% للدراسات العليا</li><li>ألا يزيد العمر عن 21 سنة للبكالوريوس، 30 للماجستير، 35 للدكتوراه</li></ul>']),
                'opportunity_type_id' => $types['scholarship'] ?? null,
                'category_id' => $categories['bachelor'] ?? null,
                'country_id' => $countries['turkey'] ?? null,
                'organization' => 'الحكومة التركية',
                'funding_type' => 'ممولة بالكامل',
                'education_level' => 'بكالوريوس، ماجستير، دكتوراه',
                'application_deadline' => '2026-02-20',
                'application_url' => 'https://www.turkiyeburslari.gov.tr',
                'official_source_url' => 'https://www.turkiyeburslari.gov.tr',
                'benefits' => json_encode(['ar' => ['رسوم دراسية كاملة', 'سكن مجاني', 'تأمين صحي', 'راتب شهري', 'تذكرة طيران', 'سنة تحضيرية للغة']]),
                'eligibility' => json_encode(['ar' => ['الجنسية: غير تركية', 'المعدل: 70%+ بكالوريوس، 75%+ دراسات عليا', 'العمر: 21- للبكالوريوس، 30- للماجستير، 35- للدكتوراه']]),
                'required_documents' => json_encode(['ar' => ['جواز سفر', 'الشهادات الدراسية', 'كشوف الدرجات', 'خطاب دافع', 'خطابات توصية', 'شهادة لغة إن وجدت']]),
                'application_process' => json_encode(['ar' => ['التسجيل عبر الموقع الرسمي', 'رفع المستندات', 'اختيار التخصصات والجامعات', 'مقابلة شخصية', 'نتيجة القبول']]),
                'status' => 'published',
                'is_featured' => true,
                'published_at' => '2026-01-15',
            ],
            [
                'title' => json_encode(['ar' => 'وظيفة مطور برمجيات في شركة تقنية كبرى بالسعودية']),
                'slug' => 'software-developer-job-saudi-arabia',
                'excerpt' => json_encode(['ar' => 'فرصة عمل مميزة لمطوري البرمجيات في شركة تقنية رائدة بالرياض براتب يصل إلى 25,000 ريال شهريًا.']),
                'content' => json_encode(['ar' => '<h2>مطور برمجيات أول - الرياض</h2><p>تبحث شركة تقنية رائدة في الرياض عن مطوري برمجيات ذوي خبرة للانضمام إلى فريق التطوير.</p><h3>المتطلبات</h3><ul><li>خبرة 3+ سنوات في تطوير الويب</li><li>إتقان Laravel و React</li><li>معرفة بقواعد البيانات MySQL و PostgreSQL</li><li>خبرة في العمل مع REST APIs</li></ul><h3>المزايا</h3><ul><li>راتب: 20,000 - 25,000 ريال</li><li>تأمين صحي</li><li>بدل سكن ومواصلات</li><li>تطوير مهني مستمر</li></ul>']),
                'opportunity_type_id' => $types['job'] ?? null,
                'category_id' => $categories['it'] ?? null,
                'country_id' => $countries['saudi-arabia'] ?? null,
                'organization' => 'شركة تقنية رائدة',
                'funding_type' => 'راتب',
                'employment_type' => 'دوام كامل',
                'salary_amount' => 25000,
                'salary_currency' => 'SAR',
                'salary_period' => 'شهري',
                'application_deadline' => '2026-03-01',
                'application_url' => 'https://example.com/apply',
                'status' => 'published',
                'is_featured' => true,
                'published_at' => '2026-02-01',
            ],
            [
                'title' => json_encode(['ar' => 'منحة جامعة قطر للدراسات العليا 2026']),
                'slug' => 'qatar-university-graduate-scholarship-2026',
                'excerpt' => json_encode(['ar' => 'منحة جامعة قطر للماجستير والدكتوراه تشمل الرسوم الدراسية والإقامة والتذاكر وراتب شهري.']),
                'content' => json_encode(['ar' => '<h2>منحة جامعة قطر للدراسات العليا</h2><p>تقدم جامعة قطر منحًا دراسية تنافسية للطلاب المتميزين من جميع الجنسيات لمتابعة دراسات الماجستير والدكتوراه.</p><h3>المزايا</h3><ul><li>إعفاء من الرسوم الدراسية</li><li>سكن جامعي</li><li>تذاكر طيران سنوية</li><li>راتب شهري 5000 ريال قطري</li></ul>']),
                'opportunity_type_id' => $types['scholarship'] ?? null,
                'category_id' => $categories['master'] ?? null,
                'country_id' => $countries['qatar'] ?? null,
                'organization' => 'جامعة قطر',
                'funding_type' => 'ممولة بالكامل',
                'education_level' => 'ماجستير، دكتوراه',
                'application_deadline' => '2026-04-15',
                'application_url' => 'https://www.qu.edu.qa',
                'status' => 'published',
                'is_featured' => true,
                'published_at' => '2026-01-20',
            ],
            [
                'title' => json_encode(['ar' => 'مؤتمر الشباب العربي للابتكار وريادة الأعمال 2026']),
                'slug' => 'arab-youth-innovation-conference-2026',
                'excerpt' => json_encode(['ar' => 'مؤتمر سنوي يجمع الشباب العربي المبتكر ورواد الأعمال في دبي لتبادل الخبرات وبناء الشبكات.']),
                'content' => json_encode(['ar' => '<h2>مؤتمر الشباب العربي للابتكار</h2><p>يجمع المؤتمر أكثر من 1000 شاب وشابة من العالم العربي لمناقشة الابتكار وريادة الأعمال والتكنولوجيا.</p>']),
                'opportunity_type_id' => $types['conference'] ?? null,
                'category_id' => $categories['business'] ?? null,
                'country_id' => $countries['uae'] ?? null,
                'organization' => 'منظمة الشباب العربي',
                'application_deadline' => '2026-05-30',
                'application_url' => 'https://example.com/conference',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-03-01',
            ],
            [
                'title' => json_encode(['ar' => 'برنامج تدريبي في شركة أرامكو السعودية للخريجين']),
                'slug' => 'aramco-graduate-training-program-2026',
                'excerpt' => json_encode(['ar' => 'برنامج تدريب منتهي بالتوظيف في أرامكو السعودية لخريجي الهندسة والعلوم والتقنية.']),
                'content' => json_encode(['ar' => '<h2>برنامج التدريب المنتهي بالتوظيف - أرامكو</h2><p>تقدم أرامكو السعودية برنامجًا تدريبيًا مكثفًا للخريجين السعوديين في مختلف التخصصات الهندسية والتقنية.</p><h3>المزايا</h3><ul><li>مكافأة شهرية خلال فترة التدريب</li><li>تأمين صحي</li><li>فرصة توظيف بعد إكمال البرنامج</li><li>تطوير مهني وشهادات معتمدة</li></ul>']),
                'opportunity_type_id' => $types['training'] ?? null,
                'category_id' => $categories['engineering'] ?? null,
                'country_id' => $countries['saudi-arabia'] ?? null,
                'organization' => 'أرامكو السعودية',
                'funding_type' => 'مكافأة تدريبية',
                'application_deadline' => '2026-06-10',
                'application_url' => 'https://www.aramco.com',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-02-15',
            ],
            [
                'title' => json_encode(['ar' => 'منحة جامعة الملك عبدالله للعلوم والتقنية KAUST']),
                'slug' => 'kaust-scholarship-2026',
                'excerpt' => json_encode(['ar' => 'منحة دراسية شاملة في جامعة الملك عبدالله للعلوم والتقنية للماجستير والدكتوراه.']),
                'content' => json_encode(['ar' => '<h2>منحة جامعة الملك عبدالله KAUST</h2><p>تقدم جامعة الملك عبدالله للعلوم والتقنية منحًا دراسية تنافسية في مجالات العلوم والهندسة والتقنية.</p><h3>المزايا</h3><ul><li>رسوم دراسية كاملة</li><li>راتب سنوي يصل إلى 30,000 دولار</li><li>سكن مجاني</li><li>تأمين صحي</li></ul>']),
                'opportunity_type_id' => $types['scholarship'] ?? null,
                'category_id' => $categories['engineering'] ?? null,
                'country_id' => $countries['saudi-arabia'] ?? null,
                'organization' => 'جامعة الملك عبدالله للعلوم والتقنية',
                'funding_type' => 'ممولة بالكامل',
                'education_level' => 'ماجستير، دكتوراه',
                'salary_amount' => 30000,
                'salary_currency' => 'USD',
                'salary_period' => 'سنوي',
                'application_deadline' => '2026-07-01',
                'application_url' => 'https://www.kaust.edu.sa',
                'status' => 'published',
                'is_featured' => true,
                'published_at' => '2026-03-01',
            ],
            [
                'title' => json_encode(['ar' => 'مسابقة هواوي العالمية لتقنية المعلومات 2026']),
                'slug' => 'huawei-ict-competition-2026',
                'excerpt' => json_encode(['ar' => 'مسابقة هواوي العالمية في تقنية المعلومات والاتصالات للطلاب مع جوائز قيمة وفرص تدريب.']),
                'content' => json_encode(['ar' => '<h2>مسابقة هواوي ICT 2026</h2><p>مسابقة عالمية تغطي مجالات الحوسبة السحابية والذكاء الاصطناعي والشبكات.</p><h3>الجوائز</h3><ul><li>المركز الأول: 20,000 دولار</li><li>شهادات معتمدة من هواوي</li><li>فرص تدريب في مراكز هواوي</li></ul>']),
                'opportunity_type_id' => $types['competition'] ?? null,
                'category_id' => $categories['it'] ?? null,
                'organization' => 'هواوي',
                'funding_type' => 'جائزة مالية',
                'application_deadline' => '2026-08-15',
                'application_url' => 'https://www.huawei.com/ict',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-04-01',
            ],
            [
                'title' => json_encode(['ar' => 'تأشيرة البحث عن عمل في ألمانيا للكفاءات']),
                'slug' => 'germany-job-seeker-visa-2026',
                'excerpt' => json_encode(['ar' => 'تأشيرة البحث عن عمل في ألمانيا لمدة 6 أشهر للكفاءات من حملة الشهادات الجامعية.']),
                'content' => json_encode(['ar' => '<h2>تأشيرة البحث عن عمل في ألمانيا</h2><p>تتيح ألمانيا للكفاءات من خارج الاتحاد الأوروبي الحصول على تأشيرة للبحث عن عمل لمدة 6 أشهر.</p><h3>الشروط</h3><ul><li>شهادة جامعية معترف بها</li><li>إثبات القدرة المالية</li><li>تأمين صحي</li></ul>']),
                'opportunity_type_id' => $types['visa'] ?? null,
                'country_id' => $countries['germany'] ?? null,
                'organization' => 'السفارة الألمانية',
                'application_deadline' => null,
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-04-10',
            ],
            [
                'title' => json_encode(['ar' => 'منحة مؤسسة قطر للتعليم والعلوم وتنمية المجتمع']),
                'slug' => 'qatar-foundation-scholarship-2026',
                'excerpt' => json_encode(['ar' => 'منح دراسية من مؤسسة قطر للطلاب المتميزين في مختلف التخصصات بالجامعات الشريكة في المدينة التعليمية.']),
                'content' => json_encode(['ar' => '<h2>منحة مؤسسة قطر</h2><p>تقدم مؤسسة قطر منحًا دراسية في جامعات عالمية داخل المدينة التعليمية مثل جامعة جورجتاون وجامعة نورثويسترن وجامعة تكساس إي أند إم.</p>']),
                'opportunity_type_id' => $types['scholarship'] ?? null,
                'category_id' => $categories['bachelor'] ?? null,
                'country_id' => $countries['qatar'] ?? null,
                'organization' => 'مؤسسة قطر',
                'funding_type' => 'ممولة بالكامل',
                'education_level' => 'بكالوريوس',
                'application_deadline' => '2026-06-30',
                'application_url' => 'https://www.qf.org.qa',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-05-01',
            ],
            [
                'title' => json_encode(['ar' => 'فرصة تطوع في منظمة الأمم المتحدة للشباب']),
                'slug' => 'un-youth-volunteer-program-2026',
                'excerpt' => json_encode(['ar' => 'برنامج الأمم المتحدة للمتطوعين الشباب يوفر فرص تطوع دولية براتب وتذاكر وتأمين.']),
                'content' => json_encode(['ar' => '<h2>برنامج متطوعي الأمم المتحدة</h2><p>يوفر برنامج متطوعي الأمم المتحدة فرصًا للشباب للمساهمة في مشاريع التنمية حول العالم.</p><h3>المزايا</h3><ul><li>راتب شهري</li><li>تذاكر طيران</li><li>تأمين صحي</li><li>إجازة سنوية مدفوعة</li></ul>']),
                'opportunity_type_id' => $types['volunteering'] ?? null,
                'organization' => 'الأمم المتحدة',
                'funding_type' => 'راتب تطوعي',
                'application_deadline' => '2026-09-30',
                'application_url' => 'https://www.unv.org',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-05-15',
            ],
            [
                'title' => json_encode(['ar' => 'منحة دراسية لدراسة الطب في جامعة القاهرة']),
                'slug' => 'cairo-university-medicine-scholarship-2026',
                'excerpt' => json_encode(['ar' => 'منحة دراسية للطلاب العرب لدراسة الطب البشري في جامعة القاهرة العريقة.']),
                'content' => json_encode(['ar' => '<h2>منحة الطب في جامعة القاهرة</h2><p>تقدم جامعة القاهرة منحًا دراسية للطلاب العرب المتفوقين لدراسة الطب البشري.</p>']),
                'opportunity_type_id' => $types['scholarship'] ?? null,
                'category_id' => $categories['medicine'] ?? null,
                'country_id' => $countries['egypt'] ?? null,
                'organization' => 'جامعة القاهرة',
                'funding_type' => 'ممولة جزئيًا',
                'education_level' => 'بكالوريوس',
                'application_deadline' => '2026-08-01',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => '2026-06-01',
            ],
            [
                'title' => json_encode(['ar' => 'وظيفة مترجم في السفارة البريطانية بالرياض']),
                'slug' => 'translator-job-british-embassy-riyadh',
                'excerpt' => json_encode(['ar' => 'وظيفة مترجم لغة عربية - إنجليزية في السفارة البريطانية بالرياض براتب مجزٍ.']),
                'content' => json_encode(['ar' => '<h2>مترجم - السفارة البريطانية بالرياض</h2><p>تبحث السفارة البريطانية في الرياض عن مترجم محترف للترجمة بين العربية والإنجليزية.</p>']),
                'opportunity_type_id' => $types['job'] ?? null,
                'country_id' => $countries['saudi-arabia'] ?? null,
                'organization' => 'السفارة البريطانية',
                'employment_type' => 'دوام كامل',
                'salary_amount' => 18000,
                'salary_currency' => 'SAR',
                'salary_period' => 'شهري',
                'application_deadline' => '2026-03-20',
                'status' => 'closed',
                'is_featured' => false,
                'published_at' => '2026-01-10',
            ],
        ];

        foreach ($opportunities as $data) {
            Opportunity::firstOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
